-- SAT Vocab schema. Single source of truth, applied by src/migrate.ts.
-- Postgres 17. Progress and analytics state is DERIVED from the append-only
-- events table (see functions.sql: record_event / rebuild_from_events).

-- ---------------------------------------------------------------------------
-- Word data (seeded once from seed_words.sql, generated by the PDF parser)
-- ---------------------------------------------------------------------------

CREATE TABLE words (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  headword text NOT NULL UNIQUE
);

CREATE TABLE senses (
  id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  word_id integer NOT NULL REFERENCES words (id) ON DELETE CASCADE,
  sense_no smallint NOT NULL CHECK (sense_no >= 1),
  pos text NOT NULL CHECK (pos IN ('v', 'n', 'adj', 'adv')),
  definition text NOT NULL CHECK (definition <> ''),
  example text,
  UNIQUE (word_id, sense_no)
);

CREATE INDEX senses_word_id_idx ON senses (word_id);
-- Quiz distractors are sampled per part of speech.
CREATE INDEX senses_pos_idx ON senses (pos);

-- ---------------------------------------------------------------------------
-- Users (anonymous; the client stores only its own UUID)
-- ---------------------------------------------------------------------------

CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Append-only event log: the source of truth for all progress + analytics.
-- No code path updates or deletes rows here; rebuild_from_events() can
-- reconstruct every derived table from this log. In a multi-role deployment
-- enforce append-only with: REVOKE UPDATE, DELETE ON events FROM app_role;
-- ---------------------------------------------------------------------------

CREATE TABLE events (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  -- Client-generated idempotency key: a retried or double-tapped action
  -- carries the same event_id and is dropped by the unique index.
  event_id uuid NOT NULL UNIQUE,
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  mode text NOT NULL CHECK (mode IN ('learn', 'quiz', 'matching', 'game')),
  type text NOT NULL CHECK (type IN ('revealed', 'rated', 'graded', 'matched', 'game_finished')),
  word_id integer REFERENCES words (id) ON DELETE SET NULL,
  sense_id integer REFERENCES senses (id) ON DELETE SET NULL,
  correct boolean,
  rating smallint CHECK (rating BETWEEN 0 AND 5),
  payload jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  -- Scoring events must carry the signal they score with.
  CHECK (type <> 'rated' OR rating IS NOT NULL),
  CHECK (type NOT IN ('graded', 'matched') OR correct IS NOT NULL)
);

CREATE INDEX events_user_created_idx ON events (user_id, created_at);

-- ---------------------------------------------------------------------------
-- Derived SM-2 state per (user, word). Maintained only by functions.sql.
-- ---------------------------------------------------------------------------

CREATE TABLE progress (
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  word_id integer NOT NULL REFERENCES words (id) ON DELETE CASCADE,
  ease numeric(4, 2) NOT NULL DEFAULT 2.50 CHECK (ease >= 1.30),
  interval_days integer NOT NULL DEFAULT 0 CHECK (interval_days >= 0),
  repetitions integer NOT NULL DEFAULT 0 CHECK (repetitions >= 0),
  due_at timestamptz NOT NULL DEFAULT now(),
  mastered_at timestamptz,
  correct_count integer NOT NULL DEFAULT 0,
  miss_count integer NOT NULL DEFAULT 0,
  last_reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, word_id)
);

-- Drives review_next(): "give me this user's due words, oldest due first".
CREATE INDEX progress_user_due_idx ON progress (user_id, due_at);

-- ---------------------------------------------------------------------------
-- Analytics rollups, maintained transactionally by record_event().
-- GET /stats reads these instead of aggregating the raw event log.
-- Days are UTC.
-- ---------------------------------------------------------------------------

CREATE TABLE user_daily_stats (
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  day date NOT NULL,
  reviews integer NOT NULL DEFAULT 0,
  correct integer NOT NULL DEFAULT 0,
  mastered integer NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, day)
);

CREATE TABLE user_mode_stats (
  user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  mode text NOT NULL CHECK (mode IN ('learn', 'quiz', 'matching', 'game')),
  attempts integer NOT NULL DEFAULT 0,
  correct integer NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, mode)
);
